apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: var-exposer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hdti/AutoSync-Off.git
    path: environments/dev/resources/nosync/var-exposer
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: var-exposer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true