apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmGlobals:
  chartHome: '../../../../../manifests'

helmCharts:
  - name: 'argo-cd'
    releaseName: argocd
    namespace: argocd
    version: 5.46.8
    includeCRDs: true
    valuesInLine:
      global:
        deploymentAnnotations:
          reloader.stakater.com/auto: "true"

resources:
- namespace.yaml

patches:
- path: ./patches/cmd-params-cm.yaml