gitops:
  env: local
  server: https://kubernetes.default.svc
  sot: https://github.com/example/gitpos.git

addons:
  enabled: true
  targetRevision: HEAD
  project: default

tenants:
  enabled: true
  targetRevision: HEAD
  project: default

nosync:
  enabled: false
  targetRevision: HEAD
  project: default