{{- if .Values.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.configuration }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}